version: '3'
services:
  nginx:
    container_name: fullstack.nginx
    image: nginx:1.13
    volumes:
      - ./:/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - php

  php:
      container_name: fullstack.php
      image: php:7.2-fpm
      volumes:
        - ./:/www